### ISSUE TITLE
User Pope

### ISSUE THREAD

**Issue by zerohab** [SageSaga/habgen-error-gits#11]
User Pope having issues logging into the hotel, I've watched him two days in row and he's sent me some screenshots over. It appears that one of the discord pluggins is interfering with his account somehow from what I know from Denis or it could be the logging logouts discord pluggin. 

17:04:31.741 [GameWorker-4-5] INFO  com.eu.habbo.habbohotel.users.Habbo  - Pope disconnected.
17:04:36.144 [HabExec-1-14  ] INFO  com.eu.habbo.habbohotel.users.Habbo  - Pope logged in 
17:04:36.149 [GameWorker-4-1] ERROR c.e.h.h.gameclients.GameClient       - Could not pass event com.eu.habbo.plugin.events.users.UserDisconnectEvent to Discord Logging
17:04:36.152 [GameWorker-4-1] ERROR c.e.h.h.gameclients.GameClient       - Caught exception

**Comment by SageSaga** [comment]
Nothing to do with login logout discord plugin at all actually. Check Pope's IP address and simply whitelist it.

**Comment by MiroVerleysen** [comment]
@zerohab this one is fixed right?

**Comment by SageSaga** [comment]
Specifically whitelisted his IP, should have no more issues. Re-open or open new issue if issue persists.
